name: Test integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: '1.21'
      - name: deploy-riab-with-ran-simulator-option
        run: |
          make riab OPT=ransim VER=stable
      - name: test
        run: |
          make test-e2-subscription
          make test-kpimon
          make test-pci
          make test-rnib
