name: Test integration
on:
  push:
    branches:
      - github-actions
  pull_request:

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy-riab-with-ran-simulator-option
        env:
          CPU_FAMILY: $(shell lscpu | grep 'CPU family:' | awk '{print $$3}')
        run: |
          echo "$CPU_FAMILY"
          make riab OPT=ransim VER=stable
      - name: test
        run: |
          make test-e2-subscription
          make test-kpimon
          make test-pci
          make test-rnib
