name: Test integration
on:
  push:
    branches:
      - github-actions
  pull_request:

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: deploy-riab-with-PCI-xAPP-option
        run: |
          echo "CPU_FAMILY:"
          lscpu | grep 'CPU family:'
          echo "CPU_Model:"
          lscpu | grep 'Model:'
          make riab OPT=ransim VER=stable
      - name: test
        run: |
          make test-e2-subscription
          make test-kpimon
          make test-pci
          make test-rnib
      - name:  deploy-riab-with-MLB-xAPP-option
        run: |
          make test-e2-subscription
          make test-kpimon
          make test-pci
          make test-mlb
          make test-rnib
      - name:  deploy-riab-with-MHO-xAPP-option
        run: |
          make test-e2-subscription
          make test-kpimon
          make test-mho
          make test-rnib
